### ISSUE TITLE
Support Swift 3

### ISSUE THREAD

**Issue by johndpope** [KevinVitale/ReactiveJSON#7]
➜  ReactiveJSON-master carthage build
*** xcodebuild output can be found in /var/folders/2b/v6zs40nx0vs6_rs6xsb897000000gp/T/carthage-xcodebuild.KMewGi.log
*** Building scheme "Nimble-iOS" in Nimble.xcodeproj
*** Building scheme "Nimble-OSX" in Nimble.xcodeproj
*** Building scheme "Nimble-tvOS" in Nimble.xcodeproj
*** Building scheme "Quick-OSX" in Quick.xcworkspace
*** Building scheme "Quick-tvOS" in Quick.xcworkspace
*** Building scheme "Quick-iOS" in Quick.xcworkspace
*** Building scheme "Result-Mac" in Result.xcodeproj
*** Building scheme "Result-tvOS" in Result.xcodeproj
*** Building scheme "Result-iOS" in Result.xcodeproj
*** Building scheme "Result-watchOS" in Result.xcodeproj
*** Building scheme "ReactiveCocoa-watchOS" in ReactiveCocoa.xcodeproj
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal armv7k
	CompileSwiftSources normal armv7k com.apple.xcode.tools.swift.compiler
(2 failures)
A shell task (/usr/bin/xcrun xcodebuild -project /Users/johnpope/Downloads/ReactiveJSON-master/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa.xcodeproj -scheme ReactiveCocoa-watchOS -configuration Release -sdk watchos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal armv7k
	CompileSwiftSources normal armv7k com.apple.xcode.tools.swift.compiler
(2 failures)

**Comment by johndpope** [comment]
my bad - 
carthage build --platform ios

**Comment by johndpope** [comment]
carthage build --platform ios
*** xcodebuild output can be found in /var/folders/2b/v6zs40nx0vs6_rs6xsb897000000gp/T/carthage-xcodebuild.PzchwK.log
*** Building scheme "Nimble-iOS" in Nimble.xcodeproj
*** Building scheme "Quick-iOS" in Quick.xcworkspace
*** Building scheme "Result-iOS" in Result.xcodeproj
*** Building scheme "ReactiveCocoa-iOS" in ReactiveCocoa.xcodeproj
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
/Users/johnpope/Downloads/ReactiveJSON-master/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Signal.swift:2:8: error: no such module 'Result'
<unknown>:0: error: unable to execute command: Segmentation fault: 11
<unknown>:0: error: compile command failed due to signal (use -v to see invocation)
A shell task (/usr/bin/xcrun xcodebuild -project /Users/johnpope/Downloads/ReactiveJSON-master/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa.xcodeproj -scheme ReactiveCocoa-iOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)

**Comment by johndpope** [comment]
carthage update seems to fix things.

**Comment by Mc2daluvin** [comment]
so how can i add this to my project because nothing seems to want to work

**Comment by KevinVitale** [comment]
It's possible _ReactiveJSON_ doesn't work with the current beta version of Xcode if that version only supports Swift 3.0 (_ReactiveJSON_ currently requires Swift 2.3).

I'll rename the issue to describe just that.

**Comment by KevinVitale** [comment]
Resolved
